In [3]:
%%capture
!pip install numpy



In [5]:
import numpy as np


[1 2 3 4]


In [11]:
list1= [1,2,3,4]
arr1 = np.array(list1, dtype=np.float64)
print(arr1)

[1. 2. 3. 4.]


In [9]:
arr1.dtype

dtype('int32')

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [15]:
arr = np.array([10, 20, 30, 40, 50])

# Access elements by index
print("First Element:", arr[0])
print("Last Element:", arr[-1])

# Slicing
print("First Three Elements:", arr[:3])
print("Elements from Index 2 to 4:", arr[2:5])


First Element: 10
Last Element: 50
First Three Elements: [10 20 30]
Elements from Index 2 to 4: [30 40 50]


In [19]:
#broadcasting
arr = np.array([1, 2, 3])
print("Array + 10:", arr * 10)


Array + 10: [10 20 30]


In [21]:
#matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise multiplication
print("Element-wise Multiplication:\n", A * B)

# Matrix multiplication (dot product)
print("Matrix Multiplication:\n", np.dot(A, B))

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [25]:
#transpose of matrix
print(A)
print(A.T)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [27]:
#Inverse
from numpy.linalg import inv

A = np.array([[1, 2], [3, 4]])
print("Inverse:\n", inv(A))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
#create a 2x3 array or random Integers between 1 and 50.Find Its Mean and Transpose.
import numpy as np
arr = np.random.randint(1,51,size=(2,3))
print("Original Array:\n",arr)
mean_value = np.mean(arr)
print("Mean:",mean_value)
transpose = arr.T
print("Transpose:\n",transpose)

Original Array:
 [[11 16  9]
 [50 27 40]]
Mean: 25.5
Transpose:
 [[11 50]
 [16 27]
 [ 9 40]]


In [31]:
A.size

4

In [33]:
#perform element-wise addition and matrix multiplication on two 2x2 matices
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise Addition:\n", A + B)
print("Matrix Multiplication:\n", np.dot(A, B))

Element-wise Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [35]:
#create a 1D array of even numbers between 10 and 20. replace all values greater than 15 with -1
import numpy as np

arr = np.arange(10, 21, 2)
print("Original Array:", arr)

arr[arr > 15] = -1
print("Modified Array:", arr)

Original Array: [10 12 14 16 18 20]
Modified Array: [10 12 14 -1 -1 -1]


In [1]:
#create a 3x3 identity Matrix and Multiply It with a Random 3x3 Matrix.
import numpy as np

identity_matrix = np.eye(3)
random_matrix = np.random.randint(1, 10, size=(3, 3))

print("Identity Matrix:\n", identity_matrix)
print("Random Matrix:\n", random_matrix)

result = np.dot(identity_matrix, random_matrix)
print("Result of Multiplication:\n", result)





Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Matrix:
 [[2 8 1]
 [5 4 2]
 [7 4 8]]
Result of Multiplication:
 [[2. 8. 1.]
 [5. 4. 2.]
 [7. 4. 8.]]
